{% set name = "ppscore" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41de7e65b3b8e9d6c1251a95f5adf0a5fb33f4ffb88cf7f27562cd9931716f5d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pandas
    - scikit-learn


test:
  imports:
    - ppscore

about:
  home: https://github.com/8080labs/ppscore
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python implementation of the Predictive Power Score (PPS)
  description: The PPS is an asymmetric, data-type-agnostic score that can detect linear or non-linear relationships between two columns.
  doc_url: https://github.com/8080labs/ppscore
  dev_url: https://github.com/8080labs/ppscore

extra:
  recipe-maintainers:
    - aschonfeld
